# Generated by Django 4.0.4 on 2022-04-20 17:38

from django.db import migrations, models
import django_ulid.models
import ulid.api.api


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', django_ulid.models.ULIDField(editable=False, primary_key=True, serialize=False)),
                ('metabase_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('cal_itp_id', models.BooleanField()),
                ('feed_name', models.BooleanField(help_text='Only used with GTFS Guidelines Date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
