# Generated by Django 4.0.4 on 2022-04-19 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ulid.models
import ulid.api.api


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('itp_id', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AgencyUser',
            fields=[
                ('id', django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
